# Generated by Django 3.1.3 on 2020-11-23 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('am', models.BooleanField(default=False)),
                ('pm', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('special', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VSL', 'VSL'), ('Ambulance', 'Ambulance')], default='Ambulance', max_length=9)),
                ('license_plate', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('arriving_time', models.DateTimeField()),
                ('is_return_path', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=255)),
                ('deposit_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_location', to='core.address')),
                ('master_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.masterrun')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('pick_up_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_location', to='core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='masterrun',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle'),
        ),
    ]
