# Generated by Django 3.1.3 on 2020-12-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201201_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
