# Generated by Django 3.1.3 on 2020-12-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201204_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterrun',
            name='users',
        ),
        migrations.AddField(
            model_name='masterrun',
            name='patients',
            field=models.ManyToManyField(to='core.Patient'),
        ),
        migrations.AlterField(
            model_name='run',
            name='master_run',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.masterrun'),
        ),
    ]
