# Generated by Django 3.1.3 on 2020-12-14 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201211_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterrun',
            name='drivers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
